# Generated by Django 4.1.1 on 2022-10-01 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete'], 'verbose_name_plural': '2. Tasks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '1. Users'},
        ),
    ]
