# Generated by Django 4.1.1 on 2022-09-27 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=50, unique=b'I01\n'),
        ),
    ]
