# Generated by Django 4.1 on 2022-10-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
