# Generated by Django 4.1 on 2022-10-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_options_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
