# Generated by Django 4.1 on 2022-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_task_create'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='create',
            new_name='Date',
        ),
        migrations.AddField(
            model_name='task',
            name='Time',
            field=models.TimeField(auto_now=True),
        ),
    ]
