# Generated by Django 4.1 on 2022-09-29 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_create_task_date_task_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='Date',
            new_name='create',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Time',
        ),
    ]
